server:
  port: 8082

spring:
  application:
    name: plan-voyage

  mail:
    host: smtp.gmail.com
    port: 587
    username: spshivampatel456@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #    Database
  datasource:
    url: jdbc:mysql://localhost:3306/plan_voyage
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#    Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/plan-voyage
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# Keycloak configuration
keycloak:
  config:
    resource-access: realm_access
    client-key: plan-voyage-client
    realm: plan-voyage
    auth-server-url: http://localhost:8081
    admin-client-id: admin-cli
    admin-client-secret: z9Ejd5Gng2ibmMfTLmGT2ZTiwfJV4S04

pixabay:
  api-key: 44181418-16a2ddd1b661940d12919d058

allowed-origin: http://localhost:5173